DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: false
DisableBodyConsumptionOnUnmarshal: false
Charset: utf8
# Mysql
Mysql.Dialect: mysql
Mysql.Prefix: jie_
Mysql.LogLevel: debug
Mysql.MaxIdleConns: 10 # 连接池的空闲数大小
Mysql.MaxOpenConns: 10 # 最大打开连接数
Mysql.ShowSql: true
Mysql.Master.User: root
Mysql.Master.Password: admin
Mysql.Master.Host: 127.0.0.1
Mysql.Master.Port: 3306
Mysql.Master.Database: csms-system
Mysql.Slave.User:
Mysql.Slave.Password:
Mysql.Slave.Host: 127.0.0.1
Mysql.Slave.Port: 3306
Mysql.Slave.Database: casbin
#Redis
Redis.Prefix: JIE_REDIES_KEY_
Redis.Exprire: 1800  # 1 * 30 * 60 * time.Second //单位秒：设置1小时
Redis.Single.Addr: localhost:6379
Redis.Single.Password:
Redis.Single.Db: 0
Redis.Single.PoolSize: 5
Redis.Cluster.Addrs: ['localhost:2181','localhost:2182']
Redis.Cluster.Password:
Redis.Cluster.State: false
#Logs
Logs.WebPath: D:/Dev/cygwin/work/golang/golang-csms-system/go-mvc/csms/logs/ #后台日志路径
Logs.AppPath: D:/Dev/cygwin/work/golang/golang-csms-system/go-mvc/web/logs/ #app日志路径
Logs.Type: JSON #日志类型 json|text
Logs.TimestampFormat: 2006-01-02 15:04:05 #日志中日期时间格式
Logs.Level: error #日志级别 ...
Logs.Out: true #控制台打印日志
Logs.MaxAge: 168  #日志最长保存多久 7 * 24 * time.Hour
Logs.RotationTime: 24 #日志默认多长时间轮转一次 24 * time.Hour
Logs.JSONPrettyPrint: true #json日志是否美化输出
Logs.JSONDataKey: #json日志条目中 数据字段都会作为该字段的嵌入字段
Logs.EnableRecordFileInfo: true #是否开启记录文件名和行号
Logs.FileInfoField:  call #文件名和行号字段名
#Jwt
JWT.Secret: JIE-- #加盐
JWT.Salt: JIESWdczx13213EDDSWQ!!@W
JWT.Timeout: 3600 #单位秒：设置1小时
#Auth
Auth.Ignores.Web: [
  '/assets',
  '/sys/user/login',
  '/sys/user/logout',
  '/sys/rule/menus',
  '/sys/test/upload']
Auth.Ignores.App: [
  '/assets',
  '/api/user/login',
  '/api/user/register']
Auth.Verify.App: [
  '/user',
  '/order']
Auth.Token: Authorization
#图片验证码验证
Captcha.Verify: false
Captcha.Key: CAPTCHA
Captcha.Exprire: 300 # 5 * 60 * time.Second 5分钟
#自定义配置
Upload.Url: http://127.0.0.1:9000/uploads
Upload.Style: ['100x100','360x360','800x800']
Upload.PicPath: ['goods/','article/','ads/']
Upload.Editor: ['images/goods/','images/article/']
#time
Timeformat: 2006-01-02 15:04:05
TimeformatShort: 2006-01-02



